model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    level_of_Laplace: 0
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: makeup
    image_size: 64
    channels: 3
    monitor: val/loss_simple_ema

#    scheduler_config: # 10000 warmup steps
#      target: ldm.lr_scheduler.LambdaLinearScheduler
#      params:
#        warm_up_steps: [ 10000 ]
#        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
#        f_start: [ 1.e-6 ]
#        f_max: [ 1. ]
#        f_min: [ 1. ]

    corr_stage_config:
      target: ldm.models.correspondence.Correspondence
      params:
        in_channels_list: [22, 83, 70]
        model_channels: 224
        num_res_blocks: 2
        channel_mult:
          - 1
          - 2
          - 3
          - 4

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 121
        out_channels: 3
        model_channels: 224
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 32
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        ckpt_path: /mnt/workspace/workgroup/sunzhaoyang/data/ldm/first_stage_models/vq-f4/model.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_unconditional__

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 4
    wrap: false
    train:
      target: ldm.data.makeup_dataset.MakeupDataset
      params:
        is_train: True
        image_path: /mnt/workspace/workgroup/sunzhaoyang/data/MakeupData2/images
        seg_path: /mnt/workspace/workgroup/sunzhaoyang/data/MakeupData2/segs
        depth_path: /mnt/workspace/workgroup/sunzhaoyang/data/MakeupData2/3d
    validation:
      target: ldm.data.makeup_dataset.MakeupDataset
      params:
        is_train: False
        image_path: /mnt/workspace/workgroup/sunzhaoyang/data/MakeupData2/images
        seg_path: /mnt/workspace/workgroup/sunzhaoyang/data/MakeupData2/segs
        depth_path: /mnt/workspace/workgroup/sunzhaoyang/data/MakeupData2/3d


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True